[workspace]
members = [
    "demo",
    "learn_trait",
    "learn_macro",
    "learn_macro_derive",
    "learn_borrow",
    "learn_slice", "learn_generics",
]
resolver = "2"
default-members = ["demo"]
